name: karbar_shop
description: A professional Flutter eCommerce application for Karbar Shop

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # HTTP requests
  http: ^1.4.0

  pdf: ^3.10.4                # For generating PDF invoices
  path_provider: ^2.1.1       # For getting file system paths
  permission_handler: ^11.0.1 # For handling storage permissions


  # State management and utilities
  provider: ^6.0.5
  shared_preferences: ^2.2.2

  # UI enhancements
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_rating_bar: ^4.0.1

  # Icons and fonts
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0

  # Image handling
  image_picker: ^1.0.4

  # Utils
  intl: ^0.19.0
  url_launcher: ^6.3.2

  share_plus: ^11.0.0
  carousel_slider: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Add custom fonts if needed
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf

  # Add app icons and images
  # assets:
  #   - images/
  #   - icons/